amount=int(input("How much money do you want to withdraw?"))
note_1=(amount//100)
note_2=(amount%100//50)
note_3=(amount%100%50//10)
amountleft=(amount%100%50%10)
print("There will be", note_1, "100 dollar notes")
print("There will be", note_2, "50 dollar notes")
print("There will be", note_3, "10 dollar notes")
print("There will be", amountleft, "1 dollar notes")